version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: bankcards-db
    restart: always
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - cards-net

volumes:
  pgdata:

networks:
  cards-net:
    name: bankcards-api-net
    driver: bridge