spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankcards}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: ${SPRING_LIQUIBASE_CHANGE_LOG:classpath:db/migration/db.changelog-master.yaml}

server:
  port: 8080

app:
  crypto:
    key: "${CRYPTO_KEY:lq9cjTL/c/6S8+/ze8YfsvdGY0BFAG05cjDEXUaRM64=}"
  jwt:
    secret: "${JWT_SECRET:dXJ5kQ5k0dFQ8FzR8rq3Zc5o2JzE7o0PZbS3mP4f8V8kq4h3pD9h2bR6kW9mT7jH}"
    expiration: 600m

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json